[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Axel Lindeberg <axel.ew.lindeberg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
regex = "1.4"
